---
- hosts: all
  roles:
    - locale
    - timezone
    - ssh_setup

- hosts: kubernetesnodes
  roles:
    - docker_setup
    - k8s_setup

- hosts: webservers
  roles:
    - nginx_setup

- hosts: gameservers
  roles:
    - minecraft_setup
