---
- name: "Setup docker"
  become: true
  vars:
    # Used when adding docker repo
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }
  block:
    - name: "Install docker install dependencies"
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: "Add docker GPG key"
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present

    - name: "Add docker repository"
      apt_repository:
        update_cache: true
        repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: "Install docker packages"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: "Ensure the docker daemon is running"
      service:
        name: docker
        enabled: true
        state: started

    - name: "Add ansible user to docker group"
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true