---
- name: "Update and upgrade all apt packages"
  become: true
  apt:
    update_cache: true
    upgrade: yes
    cache_valid_time: 3600

- name: "Check if a reboot is required"
  stat:
    path: "/var/run/reboot-required"
  register: reboot_required

- name: "Reboot machine if necessary"
  become: true
  reboot:
    reboot_timeout: 180
  when: "reboot_required.stat.exists == true"
