---
- name: "Setup k8s (kubelet, kubeadm, kubectl)"
  become: true
  block:
    - name: "Install k8s install dependencies"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: "Add k8s GPG key"
      apt_key:
        url: https://dl.k8s.io/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/kubernetes.gpg
        state: present

    - name: "Add k8s repository"
      apt_repository:
        update_cache: true
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: "Install k8s packages"
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: "Pin k8s package versions"
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
    
    - name: "Ensure systemd-resolved is enabled and running"
      service:
        name: "systemd-resolved"
        enabled: true
        state: "started"
    
    - name: "Export KUBECONFIG for root"
      lineinfile:
        path: "/root/.profile"
        line: 'export KUBECONFIG="/etc/kubernetes/kubelet.conf"'
        state: present